//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIcurd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDec
    {
        public int JobID { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public string JobCategory { get; set; }
    }
}
